import bag from "../../public/assets/Images/bag.svg";
import aboutUsPic from "../../public/assets/Images/aboutUs.jpg";
import res from "../../public/assets/Images/Res.jpg";
import logoImg from "../../public/assets/Images/logo.png";
import Cake from "../../public/assets/Images/cake.jpg";
import logoIcon from "../../public/assets/Images/logoImg.png";
import navIcon from "../../public/assets/Images/navLogo.png";
import chefImg from "../../public/assets/Images/chef.jpg";
import wineImg from "../../public/assets/Images/wine.jpg";
import eventImg from "../../public/assets/Images/events.jpg";
import chefsImg from "../../public/assets//Images/chefs.jpg";
import fishImg from "../../public/assets/Images/fish.jpg";
import coffeeMenu from "../../public/assets/Images/coffeeMenu.png";
import cupImg from "../../public/assets/Images/cup.png";
import coffeebeansImg from "../../public/assets/Images/coffeebeans.png";
import coffeeMenu1 from "../../public/assets/Images/coffeeMenu1.png";
import coffeeMenu2 from "../../public/assets/Images/coffeeMenu2.png";
import DeliciousFoodImg from "../../public/assets/Images/DeliciousFood.jpg";
import beverages from "../../public/assets/Images/beverages.jpg";
import Desserts from "../../public/assets/Images/Desserts.jpg";
import Soup from "../../public/assets/Images/Soups.jpg";
import WineBottle from "../../public/assets/Images/wineBottle.jpg";
import Video from "../../public/assets/Images/HomeVideo.mp4";
import OnionImg from "../../public/assets/Images/Onion.png";
import CorianderImg from "../../public/assets/Images/Coriander.png";
import FlowerImg from "../../public/assets/Images/Flower.png";
import Concept from "../../public/assets/Images/Concept.jpg";
import FruitsImg from "../../public/assets/Images/Fruits.jpg";
import RecipeImg from "../../public/assets/Images/Recipe.jpg";
import FlavoursImg from "../../public/assets/Images/Flavours.jpg";
import Flavours2Img from "../../public/assets/Images/Flavours2.jpg";
import MirchiImg from "../../public/assets/Images/Mirchi.png";
import Flower2Img from "../../public/assets/Images/Flower2.png";
import ReservationImg from "../../public/assets/Images/Reservation.jpg";
import LeafImg from "../../public/assets/Images/Leaf.png";
import OrangeImg from "../../public/assets/Images/Orange.png";
import logo1Img from "../../public/assets/Images/logo1.png";
export const logo = logoImg;
export const bagImg = bag;
export const rest = res;
export const cake = Cake;
export const icon = logoIcon;
export const navbarLogo = navIcon;
export const chef = chefImg;
export const wine = wineImg;
export const event = eventImg;
export const aboutPic = aboutUsPic;
export const chefImgs = chefsImg;
export const fish = fishImg;
export const coffeeMenuImg = coffeeMenu;
export const cups = cupImg;
export const coffeeBeansImg = coffeebeansImg;
export const coffeeMenu1Img = coffeeMenu1;
export const coffeMenu2Img = coffeeMenu2;
export const deliciousFood = DeliciousFoodImg;
export const beverageImg = beverages;
export const dessertsImg = Desserts;
export const soupImg = Soup;
export const wineBottleImg = WineBottle;
export const HomeVideo = Video;
export const Onion = OnionImg;
export const Coriander = CorianderImg;
export const Flower = FlowerImg;
export const ConceptImg = Concept;
export const Fruits = FruitsImg;
export const Recipe = RecipeImg;
export const Flavourss = FlavoursImg;
export const Flavours2 = Flavours2Img;
export const Mirchi = MirchiImg;
export const Flower2 = Flower2Img;
export const Reservations = ReservationImg;
export const Leaf = LeafImg;
export const Orange = OrangeImg;
export const logo1 = logo1Img;
